
        
<form action="<?php echo base_url();?>transaction/save_chargo_manifest" method="post" enctype="multipart/form-data" autocomplete="off" name="formcargo[0]" id="formcargo" onSubmit="return cek_checked();">

<div class="container">
<div class="info-box">
     <div class="col-sm-3 col-xs-4"><i class="fa fa-paste"></i></div>
     <div class="col-sm-9 col-xs-8">Create Release</div>
</div>
</div>

  <!--LEFT INPUT-->
  <div class="col-sm-6">      
  
 <div class="form-group">
        <label class="col-sm-11"> No Cargo Release</label></strong>
          <div class="col-sm-11">
           <input name="noconote" type="text" class="form-control"  id="name" placeholder="generated by system" readonly style="width:180px"/>
          </div>
</div>
 <div class="form-group">
          <strong><label class="col-sm-11"> Date</label></strong>
          <div class="col-sm-11">
            <input name="tgl3" type="text" class="form-control"  id="tgl3" required value="<?php echo date("Y-m-d") ;?>" readonly style="width:180px;"/>
          </div>
</div>
<div class="form-group">
          <label class="col-sm-11">Air Lines</label></strong>
          <div class="col-sm-11"><span class="col-sm-7">
            <select name="airlines" id="airlines" class="form-control" required="required">
            <option value="">Select Airlines</option>
        <?php 
		foreach($airline as $air){
		?>
          <option value="<?php echo $air->AirLineCode;?>"><?php echo $air->AirLineName;?></option>    
	<?php } ?>
            </select>
          </span></div>
</div>
 

</div>
      
<!--RIGHT INPUT-->
 <div class="col-sm-5" style="border:1px #CCC solid;box-shadow:2px 3px 8px #CCC; margin-right:5px; display:none">
 
<table width="200" border="0" class="table table-stripped" id="tblcargo">
  <tr>
    <td colspan="5"><h3>List SMU</h3></td>
    </tr>
  <tr style="background:#eee; color:#2283C5">
    <td>Smu</td>
    <td>Destination</td>
    <td>PCS</td>
    <td>CWT</td>
    <td>Action</td>
  </tr>
  
<tbody>


</tbody>
</table>

 
 </div>  
   

                                
           
 
  <div class="container">
                <div class="col-lg-11 portlets ui-sortable">
                    <div class="panel">
                        <!--<div class="panel-header"></div>-->
                        
                                    <div class="form-group">
<h2><span class="label label-large label-inverse "><strong>List SMU</strong></span></h2>
                                        <div class="table-responsive" id="divflight">
                                        <table class="table table-striped table-bordered table-hover" id="tbllist">
                                              <thead>
                                                <tr align="left">
                                                  <th>Flight</th>
                                                  <th><div align="left">No SMU</div></th>
                                                  <th><div align="center">Destination</div></th>
                                                  <th>PCS</th>
                                                  <th><div align="center">CWT</div></th>
                                                  <th class="text-center"><div align="center">
                                                    <input type="checkbox" name="checkall22" id="checkall22" onClick="return Checkall()" value="Check all">
                                                  </div></th>
                                                </tr>
                                          <tbody>
                                          <tbody>
 <?php 
 $no=1;
 foreach ($smu as $row) {
	 	 $air=explode('/',$row->FlightNumbDate1);
	 $kode=$air[0];
	 $cwt=$row->CWT;
	 $t_cwt+=$cwt;
	 if($cwt <=0){
		$cwt="<span class='label label-warning'>empty</span>";
	 }
	 
	 $pcs=$row->PCS;
	 $t_pcs+=$pcs;
	 if($pcs <=0){
		$pcs="<span class='label label-warning'>empty</span>";
	 }
	 
  ?>

                                            <?php $no++;} ?>
                                               
                                                 <tr align="right">
                                                  <td colspan="3">&nbsp;</td>
                                                  <td align="right"><div align="right"></div></td>
                                                  <td>&nbsp;</td>  
                                                  <td>&nbsp;</td>
                                                </tr>
                                                
                                          </tbody>
                                          </table>
                                      </div>
                                    </div>
  
  <!-- LEFT INPUT  -->
  <!-- END LEFT INPUT -->
  <!-- RIGHT INPUT  -->
                                            <div class="col-md-6">
                                              <div class="row">
                                                <div class="col-md-12"></div>
                                              </div>
                                            </div>
  <!-- END RIGHT INPUT -->
<div class="row">
 <div class="col-sm-8">
         <div class="form-group">
         <div class="col-sm-4">Submitted By</div>
          <div class="col-sm-7">
            <input name="created" type="text" class="form-control" id="created" size="" value="<?php echo $this->session->userdata('nameusr');?>" readonly>
          </div>
         </div>
         <div class="form-group">
         <div class="col-sm-4">Carried By</div>
          <div class="col-sm-7">
            <input name="carry" type="text" class="form-control" id="carry" required>
          </div>
         </div>
         <div class="form-group">
         <div class="col-sm-4">Received By</div>
          <div class="col-sm-7">
            <input name="receive" type="text" class="form-control" id="receive"  required>
          </div>
         </div>
  <div class="form-group">
          <label class="col-sm-4"> Remarks</label>
          <div class="col-sm-7">
            <textarea name="details" id="details" class="form-control"></textarea>
          </div>
</div>
 </div>  
</div>

                                    
  
                  </div>
  
                                    
                                  <div class="cpl-sm-12"><h2>&nbsp;</h2>

  
                                  <div class="row">
                                      <div class="col-md-4"></div>
                                        <div class="col-md-2">
                                            <a class="btn btn-danger " href="<?php echo base_url();?>transaction/domesctic_outgoing_house" data-toggle="modal" title="Add"><i class="icon-reply bigger-120 icons"></i>Cancel </a>
                                        </div>
                                         <div class="col-md-2">
                                             <button class="btn btn-primary" type="submit"><i class="icon-save bigger-160 icons">&nbsp;</i> Save</button>
                                        </div>  </div>     
              </div>
          </div>
  </div>

</form>
      
      
    <!--adding form-->

<div id="modalcargo" class="modal fade responsive" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    
    <div class="modal-dialog modal-" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 id=""><small>Detail </small> Flight</h3>
            </div>
            <div class="smart-form scroll">

                    <div class="modal-body">
                   
                        <div id="tabledetailhouse">
                        <table id="tbldet" class="table table-striped table-bordered" cellspacing="0" width="100%">
      <thead>
        <tr>
          <th>House</th>  
          <th>Shipper</th>
          <th> PCS</th>
          <th>CWT</th>
          <th style="width:125px;">Amount</th>
        </tr>
      </thead>



    </table>

                        </div>
                     
                     
              </div>
            
           
          </div>
        </div>
    </div>
    </div>
<!--adding form-->
<div id="modalhouse" class="modal fade responsive" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 id=""><small>Detail </small> House</h3>
            </div>
            <div class="smart-form scroll">

                    <div class="modal-body">
                   
                        <div id="divhouse">
                        <table id="tbldet" class="table table-striped table-bordered" cellspacing="0" width="100%">
      <thead>
        <tr>
          <th>House</th>  
          <th>Shipper</th>
          <th> PCS</th>
          <th>CWT</th>
          <th style="width:125px;">Amount</th>
        </tr>
      </thead>



    </table>

                        </div>
                     
                     
              </div>
            
           
          </div>
        </div>
    </div>
    </div>
    


<script type="text/javascript">  

$("#flightnumber").change(function(){
	var etd=$("#tgl3").val();
	var flihgtno=$("#flightnumber").val();
		 $.ajax({
         type: "POST",
         url : "<?php echo base_url('transaction/filter_release'); ?>",
         data: "etd="+etd+"&flihgtno="+flihgtno,
		 success: function(data){
		 $('#contenrelease').html(data);
            }
          
	   });
	
});
$("#airlines").change(function(){
			swal({
		title:'<div><i class="fa fa-spinner fa-spin fa-4x blue"></i></div>',
		text:'<p>Loading Content.......</p>',
		showConfirmButton:false,
		//type:"success",
		html:true
		});
	var airlines=$("#airlines").val();
		 $.ajax({
         type: "POST",
         url : "<?php echo base_url('transaction/filter_flight'); ?>",
         data: "airlines="+airlines,
		 success: function(data){
			 swal.close();
		 $('#divflight').html(data);
            }
          
	   });
	
});


function detailCargo(myid){
		swal({
		title:'<div><i class="fa fa-spinner fa-spin fa-4x blue"></i></div>',
		text:'<p>Loading Content.......</p>',
		showConfirmButton:false,
		//type:"success",
		html:true
		});
	var flight=$(myid).val();	
	
			$.ajax({
                type: "POST",
                url : "<?php echo base_url('transaction/detail_cargo'); ?>",
				 data: "flight="+flight,
                cache:false,
                success: function(data){
					swal.close();
					$("#modalcargo").modal('show');
                    $('#tabledetailhouse').html(data);
                    //document.frm.add.disabled=false;
                }
            });
	
}

</script>

</thead>

